### ISSUE TITLE
Reach out to our AWS colleague - to discover any challenges they are aware of, and to define any collaboration timing.

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/awscli-login#101]
## Tasks

+ [x] reach out
+ [x] meet to discuss

**Comment by ddriddle** [comment]
I scheduled an appointment for next Wednesday at 3:00 PM.

**Comment by ddriddle** [comment]
The AWS reps agreed that using the following method should work well with Terraform:

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html

The AWS reps also suggested SSO which Keith and I evaluated before and found lacking due to its dependence on a web browser. I believe, It also would require changes to the IdP that were not desirable at the time.

I talked with Chris Bell and Chris Kuehn. Neither was aware of any developer resources to help with the AWS CLI v2 migration. I reached out again to Jon for clarification on that point.
