### ISSUE TITLE
Process daemonize

### ISSUE THREAD

**Issue by chrisortman** [techservicesillinois/awscli-login#31]
Hi, I'm trying to learn about and understand how all this works. Why does the process need to daemonize itself? It seems like if i kill the process (on macOS) everything still works like it should?

**Comment by ddriddle** [comment]
You are correct that you can use the `awscli` after a successful login even if you kill the daemon. The issue is that after an hour or less, depending on how your IdP and your Amazon accounts are configured, your AWS credentials will expire. The program runs in the background only to support renewals. Renewals continue as long as the cookie returned by the IdP is valid. 

On initial login the user is prompted for their username and password.  The username and password are used to authenticate to the configured IdP using SAML ECP to retrieve a valid SAMLAssertion.
ECP works over http, so to avoid reauthenticating more than necessary the cookie returned by the server is saved to disk. If a valid cookie already exists then the user is not prompted for their username and password.

Next the SAMLAssertion is parsed for valid roles. After the user selects a role, the [AssumeRoleWithSAML](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html) API call is made. The user's desired role and the SAMLAssertion are sent to Amazon. Amazon then returns Temporary Security Credentials [(STS)](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html) that the tool stores in `~/.aws/credentials` in the user selected profile. Then tool forks into the background, goes to sleep until a few minutes before the STS credentials expire, when it wakes up it uses the cookie to authenticate against the IdP avoiding a password prompt to the user, then gets new STS credentials from Amazon. Once the cookie is expired the daemon terminates.

If you would like more information I can send you a presentation I did on how this tool works.

**Comment by chrisortman** [comment]
That's really helpful thank you! If you already have a presentation about it put together I'd be glad to look at that too.
