### ISSUE TITLE
Wrong type given for duration seconds

### ISSUE THREAD

**Issue by ezmac** [techservicesillinois/awscli-login#38]
related to #22, it looks like in the 0.1.0a6 release on pypi, DurationSeconds is set to type "string" where as botocore expects an integer.  Looks like it was introduced in 2eefc876c6b906767fcf9c9d2cdb0815f6a533da.
If you can give me an update on branch and testing procedure, I can give you a PR, I think.

**Comment by ddriddle** [comment]
@ezmac this bug has been fixed in the lasted release: version 0.2b1. I went ahead and fixed the problem myself, but thank you very much for the offer of a pull request. 

The release process is now fully automated so unit tests will be run automatically on every push to a pull request. In addition, I have written an incomplete [Developer's Guide](https://github.com/techservicesillinois/awscli-login/wiki/Developer-Guide-(WIP)) that will help you to get the unit tests running locally on Windows or Unix systems. Pull requests are very much appreciated. Thank you for your previous work!
